services:
  - type: web
    name: senaite-lims
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./bin/instance fg
    healthCheckPath: /
    healthCheckTimeoutSeconds: 120
